name: Build and Deploy Docs

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository 🛎️
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.DOCS_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.DOCS_AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'

      - name: Install AWS CLI v2
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o /tmp/awscliv2.zip
          unzip -q /tmp/awscliv2.zip -d /tmp
          rm /tmp/awscliv2.zip
          sudo /tmp/aws/install --update
          rm -rf /tmp/aws/

      - name: Install Dependencies
        run: yarn install

      - name: Build Project
        run: yarn export

      - name: Deploy to S3
        if: github.ref == 'refs/heads/main' || github.event_name != 'pull_request'
        run: yarn deploy:ci

      - name: Invalidate CloudFront
        if: github.ref == 'refs/heads/main' || github.event_name != 'pull_request'
        run: yarn invalidate:ci

      - name: Prepare seo
        if: github.ref == 'refs/heads/main' || github.event_name != 'pull_request'
        run: bash ./seo/prepare.sh
